### ISSUE TITLE
Add Windows support for PVM release builds

### ISSUE THREAD

**Issue by perigrin** [perigrin/pvm#3]
## Summary

Add Windows platform support to PVM's release build pipeline. Currently the release workflow only builds for Linux and macOS platforms, limiting PVM's accessibility on Windows development environments.

## 🔧 **Complexity Estimate: Medium (4,000-6,000 tokens)**

**Implementation breakdown:**
- GitHub Actions workflow modifications (~1,000 tokens)
- Makefile Windows compatibility fixes (~1,500 tokens)
- Tree-sitter Windows build resolution (~2,000 tokens)
- Documentation updates (~1,000 tokens)

**Key challenges:** CGO compilation complexity, cross-platform testing requirements

## Current Limitation

The GitHub Actions release workflow (`.github/workflows/release.yml`) only supports:
- `linux-amd64`
- `linux-arm64` (removed in recent commits)
- `darwin-amd64` (Intel Mac)
- `darwin-arm64` (Apple Silicon)

**Missing**: `windows-amd64` and potentially `windows-arm64`

### 1. Tree-sitter CGO Compilation
The main blocker is tree-sitter-typed-perl CGO compilation on Windows:
- C compiler requirements (MinGW/MSVC)
- Header file paths and linking
- Cross-compilation complexity

### 2. Build Tool Dependencies
- Node.js/npm for tree-sitter-cli
- Make compatibility (Windows doesn't have make by default)
- Shell script compatibility

### 3. Binary Distribution
- Windows executable naming (`.exe` extension)
- Archive format preferences (`.zip` vs `.tar.gz`)
- Security considerations (unsigned binaries, SmartScreen)

### Update Build Matrix

```yaml
# .github/workflows/release.yml
jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux-amd64
          - runner: macos-latest
            platform: darwin-amd64
          - runner: macos-14  # Apple Silicon
            platform: darwin-arm64
          - runner: windows-latest  # NEW
            platform: windows-amd64
```

### Windows-Specific Build Steps

```yaml
- name: Install dependencies (Windows)
  if: runner.os == 'Windows'
  run:  < /dev/null | 
    # Install Node.js and tree-sitter-cli
    npm install -g tree-sitter-cli
    
    # Install build tools
    choco install make mingw
    
    # Set up CGO environment
    echo "CGO_ENABLED=1" >> $GITHUB_ENV
    echo "CC=gcc" >> $GITHUB_ENV

- name: Build tree-sitter (Windows)
  if: runner.os == 'Windows'
  run: |
    cd tree-sitter-typed-perl
    make generate
    # Windows-specific build commands
```

### Makefile Windows Compatibility

```makefile
# Detect platform
ifeq ($(OS),Windows_NT)
    detected_OS := Windows
    EXE_EXT := .exe
    ARCHIVE_CMD := powershell Compress-Archive
    ARCHIVE_EXT := .zip
else
    detected_OS := $(shell uname -s)
    EXE_EXT := 
    ARCHIVE_CMD := tar -czf
    ARCHIVE_EXT := .tar.gz
endif

# Platform-specific build targets
build-windows:
	CGO_ENABLED=1 go build -o build/pvm$(EXE_EXT) ./cmd/pvm

# Cross-compilation for Windows from Linux
cross-compile-windows:
	GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc \
	go build -o build/pvm-windows-amd64.exe ./cmd/pvm
```

### Tree-sitter Windows Build

Address the CGO compilation issues:

```bash
# Install Windows build dependencies in CI
- name: Setup Windows build environment
  if: runner.os == 'Windows'
  run: |
    # Install MSYS2 for better Unix tool compatibility
    choco install msys2
    
    # Install gcc and make through MSYS2
    C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc make"
    
    # Add to PATH
    echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
```

### Archive Creation

```yaml
- name: Create Windows archive
  if: matrix.platform == 'windows-amd64'
  run: |
    cd build/release
    powershell Compress-Archive -Path pvm-windows-amd64.exe -DestinationPath pvm-${{ env.VERSION }}-windows-amd64.zip
```

### Local Windows Testing
```bash
# Test in Windows environment
git clone https://github.com/perigrin/pvm.git
cd pvm

# Install dependencies
choco install nodejs make mingw
npm install -g tree-sitter-cli

# Build
make

# Test basic functionality
./build/pvm.exe version
./build/pvm.exe available
```

### CI Validation
- Full build and test suite on Windows runners
- Cross-platform integration tests
- Binary functionality verification

### Installation Instructions
```markdown
## Windows Installation

### Option 1: Release Binary
```powershell
# Download latest release
Invoke-WebRequest -Uri "https://github.com/perigrin/pvm/releases/download/v1.0.0/pvm-1.0.0-windows-amd64.zip" -OutFile "pvm.zip"

# Extract
Expand-Archive -Path "pvm.zip" -DestinationPath "C:\Program Files\pvm"

# Add to PATH
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\pvm", "User")
```

### Option 2: Build from Source
```powershell
# Prerequisites
choco install nodejs make mingw git

# Build
git clone https://github.com/perigrin/pvm.git
cd pvm
make
```

## Success Criteria

1. **Automated Builds**: Windows binaries built automatically in CI
2. **Functionality Parity**: All core PVM features work on Windows
3. **Easy Installation**: Simple download and install process
4. **Documentation**: Clear Windows-specific setup instructions
5. **Testing**: Comprehensive test coverage on Windows platform

## Benefits

- **Broader Adoption**: Access to Windows development community
- **Team Compatibility**: Mixed-platform development teams
- **CI/CD Integration**: Windows-based build systems can use PVM
- **Enterprise Support**: Many enterprises use Windows development environments

This addition would make PVM truly cross-platform and accessible to the full spectrum of Perl developers.
